import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { store } from "@/lib/store";

type Lang = "en" | "ar";

const translations = {
  en: {
    appName: "dawaa+",
    home: "Home",
    medications: "Medications",
    history: "History",
    settings: "Settings",
    todaySummary: "Today's Medication Summary",
    schedule: "Schedule",
    taken: "Taken",
    missed: "Missed",
    bloodPressure: "Blood Pressure",
    appointments: "Appointments",
    labTests: "Lab Tests",
    upcomingDoses: "Upcoming Doses",
    noDosesToday: "No doses today",
    addMedication: "Add Medication",
    noMedications: "No medications",
    addFirstMedication: "Add your first medication",
    medicationName: "Medication Name",
    form: "Form",
    dosage: "Dosage",
    frequency: "Frequency",
    times: "Times",
    mealRelation: "Meal Relation",
    notes: "Notes",
    stock: "Stock",
    currentStock: "Current Stock",
    stockAlert: "You will be alerted when stock reaches 20%",
    confirm: "Confirm",
    next: "Next",
    previous: "Previous",
    save: "Save",
    concentration: "Concentration",
    concentrationUnit: "mg",
    cancel: "Cancel",
    basicInfo: "Basic Info",
    pills: "Pills",
    capsules: "Capsules",
    liquid: "Liquid",
    injection: "Injection",
    drops: "Drops",
    cream: "Cream",
    inhaler: "Inhaler",
    patches: "Patches",
    onceDaily: "Once daily",
    twiceDaily: "Twice daily",
    threeTimesDaily: "Three times daily",
    fourTimesDaily: "Four times daily",
    everyXHours: "Every X hours",
    specificDays: "Specific days",
    everyWeek: "Every week",
    every2Weeks: "Every 2 weeks",
    everyMonth: "Every month",
    noPreference: "No preference",
    beforeMeal: "Before meal",
    afterMeal: "After meal",
    withMeal: "With meal",
    bloodPressureMonitoring: "Blood Pressure Monitoring",
    latestReading: "Latest Reading",
    averageOfLast: "Average of last",
    readings: "readings",
    normal: "Normal",
    elevated: "Elevated",
    high: "High",
    printReport: "Print Report for Doctor",
    recordNewReading: "Record New Reading",
    enterBP: "Enter blood pressure readings (upper & lower)",
    systolicUpper: "Systolic (Upper)",
    diastolicLower: "Diastolic (Lower)",
    heartRate: "Heart Rate",
    normalRange: "Normal range: 60 - 100 bpm",
    measurementPeriod: "Measurement Period",
    morning: "Morning",
    evening: "Evening",
    saveReading: "Save Reading",
    medicalTip: "Medical Tip",
    medicalTipText: "It is recommended to measure blood pressure twice daily, in the morning before taking medications, and in the evening. Make sure to sit quietly for 5 minutes before measuring.",
    readingsLog: "Readings Log",
    dateTime: "Date & Time",
    reading: "Reading",
    actions: "Actions",
    noAppointments: "No appointments",
    addFirstAppointment: "Add your first appointment",
    addAppointment: "Add Appointment",
    all: "All",
    upcoming: "Upcoming",
    completed: "Completed",
    specialty: "Specialty",
    generalPractitioner: "General Practitioner",
    dentist: "Dentist",
    cardiologist: "Cardiologist",
    dermatologist: "Dermatologist",
    ophthalmologist: "Ophthalmologist",
    orthopedist: "Orthopedist",
    neurologist: "Neurologist",
    other: "Other",
    appointmentDate: "Appointment Date",
    appointmentTime: "Appointment Time",
    location: "Location",
    reminderBefore: "Reminder before dose",
    atTime: "At time",
    min5: "5 minutes",
    min10: "10 minutes",
    min15: "15 minutes",
    min30: "30 minutes",
    min60: "60 minutes",
    min120: "120 minutes",
    noLabTests: "No lab tests yet",
    addFirstLabTest: "Add your first lab test",
    addLabTest: "Add Lab Test",
    testName: "Test Name",
    doseHistory: "Dose History",
    noHistory: "No history yet",
    language: "Language",
    userName: "User Name",
    notifications: "Notifications",
    enabled: "Enabled",
    disabled: "Disabled",
    scheduled: "scheduled",
    voiceNotifications: "Voice Notifications",
    voiceNotificationsDesc: "Read medication names aloud when reminders fire - great for elderly users",
    escalationOnMissed: "Escalation on missed doses",
    escalationDesc: "Notify emergency contact when 2 consecutive doses are missed",
    emergencyContact: "Emergency Contact",
    about: "About",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    contactUs: "Contact Us",
    version: "Version",
    signOut: "Sign Out",
    deleteAccount: "Delete Account & All Data",
    markDone: "Mark done",
    done: "Done",
    medicationNotFound: "Medication not found in database. Please verify the name.",
    medicationVerified: "Medication name verified ✓",
    uploadFile: "Upload Lab Results File",
    uploadLabFile: "Tap to upload PDF, JSON, or text file",
    analyzingFile: "Analyzing file...",
    clickToChange: "Click to change file",
    analysisResults: "Analysis Results",
    testsFound: "tests found",
    noResultsFound: "Could not extract lab values from this file. Try a different format.",
    normalResults: "Normal",
    abnormalResults: "Abnormal",
    needsAttention: "Needs Attention",
    normalResultsTitle: "Normal Results",
    normalRangeLabel: "Normal range",
    aboveNormal: "Above normal",
    belowNormal: "Below normal",
    viewResults: "View Results",
    hideResults: "Hide",
    analyzedResults: "Analyzed results",
    ocrProcessing: "Reading image (OCR)...",
    manualEntry: "Manual Entry",
    custom: "Custom",
    enterValue: "Enter value",
    addTestItem: "Add Test",
    searchTests: "Search tests...",
    customTest: "Custom test (not in list)",
    enterCustomTestName: "Enter test name",
    add: "Add",
  },
  ar: {
    appName: "+دواء",
    home: "الرئيسية",
    medications: "الأدوية",
    history: "السجل",
    settings: "الإعدادات",
    todaySummary: "ملخص أدوية اليوم",
    schedule: "مجدولة",
    taken: "تم أخذها",
    missed: "فائتة",
    bloodPressure: "ضغط الدم",
    appointments: "المواعيد",
    labTests: "التحاليل",
    upcomingDoses: "الجرعات القادمة",
    noDosesToday: "لا جرعات اليوم",
    addMedication: "إضافة دواء",
    noMedications: "لا توجد أدوية",
    addFirstMedication: "أضف أول دواء لك",
    medicationName: "اسم الدواء",
    form: "الشكل",
    dosage: "الجرعة",
    frequency: "التكرار",
    times: "الأوقات",
    mealRelation: "علاقة بالوجبة",
    notes: "ملاحظات",
    stock: "المخزون",
    currentStock: "المخزون الحالي",
    stockAlert: "سيتم تنبيهك عندما يصل المخزون إلى 20%",
    confirm: "تأكيد",
    next: "التالي",
    previous: "السابق",
    save: "حفظ",
    concentration: "التركيز",
    concentrationUnit: "ملغ",
    cancel: "إلغاء",
    basicInfo: "معلومات أساسية",
    pills: "حبوب",
    capsules: "كبسولات",
    liquid: "سائل",
    injection: "حقن",
    drops: "قطرات",
    cream: "كريم",
    inhaler: "بخاخ",
    patches: "لصقات",
    onceDaily: "مرة يومياً",
    twiceDaily: "مرتين يومياً",
    threeTimesDaily: "ثلاث مرات يومياً",
    fourTimesDaily: "أربع مرات يومياً",
    everyXHours: "كل X ساعات",
    specificDays: "أيام محددة",
    everyWeek: "كل أسبوع",
    every2Weeks: "كل أسبوعين",
    everyMonth: "كل شهر",
    noPreference: "بدون تفضيل",
    beforeMeal: "قبل الأكل",
    afterMeal: "بعد الأكل",
    withMeal: "مع الأكل",
    bloodPressureMonitoring: "مراقبة ضغط الدم",
    latestReading: "آخر قراءة",
    averageOfLast: "متوسط آخر",
    readings: "قراءات",
    normal: "طبيعي",
    elevated: "مرتفع",
    high: "عالي",
    printReport: "طباعة تقرير للطبيب",
    recordNewReading: "تسجيل قراءة جديدة",
    enterBP: "أدخل قراءات ضغط الدم (العلوي والسفلي)",
    systolicUpper: "الانقباضي (العلوي)",
    diastolicLower: "الانبساطي (السفلي)",
    heartRate: "معدل النبض",
    normalRange: "المعدل الطبيعي: 60 - 100 نبضة/دقيقة",
    measurementPeriod: "فترة القياس",
    morning: "صباحاً",
    evening: "مساءً",
    saveReading: "حفظ القراءة",
    medicalTip: "نصيحة طبية",
    medicalTipText: "يُنصح بقياس ضغط الدم مرتين يومياً، صباحاً قبل تناول الأدوية، ومساءً. تأكد من الجلوس بهدوء لمدة 5 دقائق قبل القياس.",
    readingsLog: "سجل القراءات",
    dateTime: "التاريخ والوقت",
    reading: "القراءة",
    actions: "إجراءات",
    noAppointments: "لا توجد مواعيد",
    addFirstAppointment: "أضف أول موعد لك",
    addAppointment: "إضافة موعد",
    all: "الكل",
    upcoming: "القادمة",
    completed: "المكتملة",
    specialty: "التخصص",
    generalPractitioner: "طبيب عام",
    dentist: "طبيب أسنان",
    cardiologist: "طبيب قلب",
    dermatologist: "طبيب جلدية",
    ophthalmologist: "طبيب عيون",
    orthopedist: "طبيب عظام",
    neurologist: "طبيب أعصاب",
    other: "أخرى",
    appointmentDate: "تاريخ الموعد",
    appointmentTime: "وقت الموعد",
    location: "الموقع",
    reminderBefore: "التذكير قبل الجرعة",
    atTime: "في الوقت",
    min5: "5 دقائق",
    min10: "10 دقائق",
    min15: "15 دقائق",
    min30: "30 دقيقة",
    min60: "60 دقيقة",
    min120: "120 دقيقة",
    noLabTests: "لا توجد تحاليل بعد",
    addFirstLabTest: "أضف أول تحليل لك",
    addLabTest: "إضافة تحليل",
    testName: "اسم التحليل",
    doseHistory: "سجل الجرعات",
    noHistory: "لا يوجد سجل بعد",
    language: "اللغة",
    userName: "اسم المستخدم",
    notifications: "الإشعارات",
    enabled: "مفعّلة",
    disabled: "معطّلة",
    scheduled: "مجدولة",
    voiceNotifications: "الإشعارات الصوتية",
    voiceNotificationsDesc: "قراءة أسماء الأدوية بصوت عالٍ عند التذكير - مناسب لكبار السن",
    escalationOnMissed: "التصعيد عند تفويت الجرعات",
    escalationDesc: "إشعار جهة اتصال الطوارئ عند تفويت جرعتين متتاليتين",
    emergencyContact: "جهة اتصال الطوارئ",
    about: "حول التطبيق",
    termsOfUse: "شروط الاستخدام",
    privacyPolicy: "سياسة الخصوصية",
    contactUs: "تواصل معنا",
    version: "الإصدار",
    signOut: "تسجيل الخروج",
    deleteAccount: "حذف الحساب وجميع البيانات",
    markDone: "تم",
    done: "مكتمل",
    medicationNotFound: "الدواء غير موجود في قاعدة البيانات. يرجى التحقق من الاسم.",
    medicationVerified: "تم التحقق من اسم الدواء ✓",
    uploadFile: "رفع ملف نتائج التحاليل",
    uploadLabFile: "اضغط لرفع ملف PDF أو JSON أو نصي",
    analyzingFile: "جاري تحليل الملف...",
    clickToChange: "اضغط لتغيير الملف",
    analysisResults: "نتائج التحليل",
    testsFound: "تحليل تم العثور عليه",
    noResultsFound: "لم يتم استخراج قيم من هذا الملف. جرب صيغة أخرى.",
    normalResults: "طبيعي",
    abnormalResults: "غير طبيعي",
    needsAttention: "يحتاج انتباه",
    normalResultsTitle: "نتائج طبيعية",
    normalRangeLabel: "المعدل الطبيعي",
    aboveNormal: "أعلى من الطبيعي",
    belowNormal: "أقل من الطبيعي",
    viewResults: "عرض النتائج",
    hideResults: "إخفاء",
    analyzedResults: "نتائج محللة",
    ocrProcessing: "جاري قراءة الصورة (OCR)...",
    manualEntry: "إدخال يدوي",
    custom: "مخصص",
    enterValue: "أدخل القيمة",
    addTestItem: "إضافة فحص",
    searchTests: "ابحث عن فحص...",
    customTest: "فحص مخصص (غير موجود في القائمة)",
    enterCustomTestName: "أدخل اسم الفحص",
    add: "إضافة",
  },
};

type Translations = typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
  isRTL: false,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(store.getSettings().language);

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    const settings = store.getSettings();
    store.saveSettings({ ...settings, language: newLang });
    document.documentElement.dir = newLang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = newLang;
  };

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang], isRTL: lang === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
};
